
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_IZQUIERDA = 26;
  public static final int ERROR_IDENTIFICADOR = 67;
  public static final int FUNCTION = 45;
  public static final int OPERADOR_CORCHETE_ABRIR = 15;
  public static final int CHAR = 63;
  public static final int CONST = 43;
  public static final int OPERADOR_MULTIPLICACION = 11;
  public static final int OPERADOR_MENOR_QUE = 8;
  public static final int REPEAT = 53;
  public static final int INT = 60;
  public static final int FOR = 55;
  public static final int WRITE = 48;
  public static final int OPERADOR_SUSTRACCION = 10;
  public static final int IDENTIFICADOR = 35;
  public static final int OPERADOR_DIVISION = 12;
  public static final int NOT = 32;
  public static final int AND = 31;
  public static final int OPERADOR_ASIGNACION_DIVISION = 22;
  public static final int OPERADOR_DIFERENTE_DE = 18;
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_DERECHA = 25;
  public static final int OPERADOR_ASIGNACION_SUSTRACCION = 20;
  public static final int OR = 30;
  public static final int BEGIN = 41;
  public static final int DIV = 34;
  public static final int OPERADOR_DOS_PUNTOS = 29;
  public static final int UNTIL = 54;
  public static final int LITERAL_NUM_ENTERO = 38;
  public static final int OPERADOR_DISMINUCION = 4;
  public static final int IF = 49;
  public static final int BOOLEAN = 65;
  public static final int EOF = 0;
  public static final int TRUE = 58;
  public static final int OPERADOR_PARENTESIS_ABRIR = 13;
  public static final int PROGRAM = 40;
  public static final int OPERADOR_DESPLAZAMIENTO_IZQUIERDA = 24;
  public static final int error = 1;
  public static final int OPERADOR_PARENTESIS_CERRAR = 14;
  public static final int OPERADOR_MAYOR_IGUAL_QUE = 5;
  public static final int MOD = 33;
  public static final int PALABRA_RESERVADA = 39;
  public static final int OPERADOR_INCREMENTO = 3;
  public static final int REAL = 66;
  public static final int ERROR_PALABRA_RESERVADA = 69;
  public static final int SHORTINT = 62;
  public static final int OPERADOR_ASIGNACION_ADICION = 19;
  public static final int ERROR_OPERADOR = 70;
  public static final int ELSE = 51;
  public static final int OPERADOR_PUNTO_Y_COMA = 28;
  public static final int OPERADOR_COMA = 27;
  public static final int OPERADOR = 2;
  public static final int READ = 47;
  public static final int TO = 56;
  public static final int LITERAL_STRING = 37;
  public static final int WHILE = 52;
  public static final int OPERADOR_MENOR_IGUAL_QUE = 7;
  public static final int THEN = 50;
  public static final int ERROR_LITERAL = 68;
  public static final int END = 42;
  public static final int STRING = 64;
  public static final int OPERADOR_ADICION = 9;
  public static final int OPERADOR_ASIGNACION = 17;
  public static final int OPERADOR_DESPLAZAMIENTO_DERECHA = 23;
  public static final int OPERADOR_MAYOR_QUE = 6;
  public static final int FALSE = 59;
  public static final int OPERADOR_CORCHETE_CERRAR = 16;
  public static final int LONGINT = 61;
  public static final int PROCEDURE = 46;
  public static final int VAR = 44;
  public static final int OPERADOR_ASIGNACION_MULTIPLICACION = 21;
  public static final int DO = 57;
  public static final int LITERAL_NUM_FLOTANTE = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPERADOR",
  "OPERADOR_INCREMENTO",
  "OPERADOR_DISMINUCION",
  "OPERADOR_MAYOR_IGUAL_QUE",
  "OPERADOR_MAYOR_QUE",
  "OPERADOR_MENOR_IGUAL_QUE",
  "OPERADOR_MENOR_QUE",
  "OPERADOR_ADICION",
  "OPERADOR_SUSTRACCION",
  "OPERADOR_MULTIPLICACION",
  "OPERADOR_DIVISION",
  "OPERADOR_PARENTESIS_ABRIR",
  "OPERADOR_PARENTESIS_CERRAR",
  "OPERADOR_CORCHETE_ABRIR",
  "OPERADOR_CORCHETE_CERRAR",
  "OPERADOR_ASIGNACION",
  "OPERADOR_DIFERENTE_DE",
  "OPERADOR_ASIGNACION_ADICION",
  "OPERADOR_ASIGNACION_SUSTRACCION",
  "OPERADOR_ASIGNACION_MULTIPLICACION",
  "OPERADOR_ASIGNACION_DIVISION",
  "OPERADOR_DESPLAZAMIENTO_DERECHA",
  "OPERADOR_DESPLAZAMIENTO_IZQUIERDA",
  "OPERADOR_ASIGNACION_DESPLAZAMIENTO_DERECHA",
  "OPERADOR_ASIGNACION_DESPLAZAMIENTO_IZQUIERDA",
  "OPERADOR_COMA",
  "OPERADOR_PUNTO_Y_COMA",
  "OPERADOR_DOS_PUNTOS",
  "OR",
  "AND",
  "NOT",
  "MOD",
  "DIV",
  "IDENTIFICADOR",
  "LITERAL_NUM_FLOTANTE",
  "LITERAL_STRING",
  "LITERAL_NUM_ENTERO",
  "PALABRA_RESERVADA",
  "PROGRAM",
  "BEGIN",
  "END",
  "CONST",
  "VAR",
  "FUNCTION",
  "PROCEDURE",
  "READ",
  "WRITE",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "REPEAT",
  "UNTIL",
  "FOR",
  "TO",
  "DO",
  "TRUE",
  "FALSE",
  "INT",
  "LONGINT",
  "SHORTINT",
  "CHAR",
  "STRING",
  "BOOLEAN",
  "REAL",
  "ERROR_IDENTIFICADOR",
  "ERROR_LITERAL",
  "ERROR_PALABRA_RESERVADA",
  "ERROR_OPERADOR"
  };
}

